### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by michaelanthonymain** [michaelanthonymain/eslint-plugin-testdouble#1]
- [x] Resolve issue with the rule not being found
- [x] Ensure documentation is accurate
- [x] Publish to npm
